### PR TITLE
Update to Product Reviews and View More Button

### PR DESCRIPTION
**Pull request by MeganSpauldingCreative**
Rearranged the HTML to make it more user-friendly. Added a containing boarder around each product type to help separate out the space.

### CODE REVIEW

**Comment by chrisvneal** [comment]
This is causing a merge conflict. Try pulling the latest changes from the **[master]** branch and working out the changes, that may be the issue 🤔

**Comment by MeganSpauldingCreative** [comment]
That’s strange, because I made sure to update the branch before I tried to do the pull. 🤔I’ll check it out tomorrow.

**Comment by MeganSpauldingCreative** [comment]
I have a group project too and I had it throw an error once with everything matched and it was some random >>>>> characters with numbers github had attached. That was the only difference between their code and the master (other than the change they made of course) is it showing anything like that?

**Comment by chrisvneal** [comment]
A message detailing the conflict should have shown up for you before you made the pull request. Here's what it says on my end. I literally can't do anything to fix it, all the controls seem to be disabled.

merge_conflict

**Comment by MeganSpauldingCreative** [comment]
Hmmm very strange. I'll try to redo it right now! I will go ahead and close this pull request for now.

**Pull request closed without merging**
