### PR TITLE
Creating initial sidebar conent for index.tml

### PR DESCRIPTION
**Pull request by chrisvneal**
@GWGweb-projectgroup 

Still peeking in and taking a look at improvements. How is everyone? 

**Did everyone make it into the second phase!?**

I began creation of menu on the left side bar. Added some styles to get things going, just trying to figure out the usefulness of it all and the possibilities of it being styled differently altogether!

### CODE REVIEW

**Comment by elementWebDev** [comment]
Good job @chrisvneal coming back to the project and working on the dropdown :)

**Comment by elementWebDev** [comment]
I didnt make it lol.. But thats not stopping me... I have a hunger to keep learning and applying... Woot! Woot!

**Comment by elementWebDev** [comment]
@ddpetty thank you for your dedication... Life happens. No worries :-)

**Comment by chrisvneal** [comment]
Thanks @ddpetty , and no big deal @elementWebDev more opportunities to come! I can't wait to kick this project back into gear.

**Pull request merged**
