### PR TITLE
products.html

### PR DESCRIPTION
**Pull request by elementWebDev**
split products into sections onto products.html.

Since we're only doing 2-3 pages we should just have index, products, (cart? or about?)

### CODE REVIEW

**Comment by elementWebDev** [comment]
I will add the audio style and code to products.html

**Comment by chrisvneal** [comment]
@elementWebDev  ok, sounds good. 

Good idea to somehow just make sections on a product page. The **about page** sounds great too. I'll think of ideas to get the **index.html** going!

**Comment by elementWebDev** [comment]
Just an update... I'm still working on products page with sections. I was gathering more asset pics but figured i could leave that to someone else for now.. I'll post more in [issue #26 ](https://github.com/GWGweb-projectgroup/practice-project/issues/26)

**Comment by elementWebDev** [comment]
ok not sure if I need to make another pull request, but I have something to work with now

**Comment by elementWebDev** [comment]
Im uploading changes to [elementwebdev.com/gwg](https://elementwebdev.com/gwg)

**Comment by chrisvneal** [comment]
@elementWebDev you ready for me to merge changes? When you are, pull request to the **[dev]** branch, I'll check things out and put them onto the **[master]**.

**Comment by elementWebDev** [comment]
ready. I did a PR to dev

**Pull request closed without merging**
