### PR TITLE
Ina chemerko patch 1

### PR DESCRIPTION
**Pull request by InaChemerko**

### CODE REVIEW

**Comment by InaChemerko** [comment]
sing up

**Comment by chrisvneal** [comment]
What's that earlier commit for #59021c2

**Comment by InaChemerko** [comment]
Oh my Gosh! How can I do it? I have a big mess in my head

**Comment by chrisvneal** [comment]
Let me see, the first commit was good. You made your changes! But what was the second commit for, about adding files via upload. Did you make any changes in that commit?

**Comment by InaChemerko** [comment]
No. I only read the article and play with buttons. for practice. Maybe I did something wrong. Sorry

**Comment by chrisvneal** [comment]
Also you have to make sure your pull request is from your fork to our **practice-project** repo here, the **[dev]** branch

**Comment by InaChemerko** [comment]
How can I do it?

**Comment by chrisvneal** [comment]
That's fine. You actually did good. Play around and practice, you won't be hurting anything lol Nothing will get merged until I approve so your good

**Comment by InaChemerko** [comment]
Chris, I need to go. Thank you for your help and chance to have this experience. I come back tomorrow )))

**Comment by chrisvneal** [comment]
Ok that's fine, when you get back follow these instructions @InaChemerko 

### Make a pull request from your repo to the main project's DEV branch
1. Push the branch you made changes to on **your** local machine up to your forked repo of this project

2. Make a **pull request** for that commit, it will take you back here

3. At the top of the page, make sure the **[dev]** branch is  selected on the left, and that your branch _that you just pushed_ is selected on the right

4. Click to make the pull request, I will handle the rest from there

So you did everything correctly except next time
* make sure you're pull requesting into our **[dev]** branch, _not the **[master]**_
* only push your changes to the README file, you did that! That's all we need for now

**Pull request closed without merging**
