### PR TITLE
Cynthiaclinton dev

### PR DESCRIPTION
**Pull request by Cynth42**
Don't merge commit: 645b4a7, f25d730, 5d7c86c. Was accidentally pushed for merge.  
Please merge 922dad9.  Added carousel to Images, centered .product-header and changed my slack handler name to @Cynthia  in readme - thanks! :)

### CODE REVIEW

**Comment by cynthia** [comment]
You might not have the Github handle you think you have. :)

**Comment by Cynth42** [comment]
Really Sangwhan?  Then I need to change it soon :)

**Comment by cynthia** [comment]
You can’t change it to a name someone is already using. The handle next to your picture is the one you are currently using.

**Comment by Cynth42** [comment]
Alright, but I was actually referring to my slack handle name.  My Github handle will remain the same. it's cute - isn't it?- lol :)

**Comment by chrisvneal** [comment]
@Cynth42 I don't think merging commits work that way. Not sure I can select which of your commits to merge, you have to fix things on your end and push back those commits. Just fix and adjust the changes you made, commit those and make a pull request. You know what I mean?

And where did that unicorn come from? 😆

**Comment by Cynth42** [comment]
Hey @chrisvneal ,
Just merge all of them because the ones I told you not to merge won't make any changes to the files.  Only one of the commits will modify changes to onsale.html.  I can't make any adjustments on my side because I have already made the pull request.  If I see any unwanted changes after you merged it, I will remove it. Thank you! Oh by the way, the unicorn- I thought he was on the GWG team - lol!

**Pull request merged**
